language: python
python:
  - 3.6
  - 3.7
  - 3.8
sudo: false
install:
  - echo "install start"
  - pip install poetry
  - poetry install
  - pip install codecov
  - echo "install end"
script:
  - echo "script start"
  - python3 -m pytest --cov=fracdiff
  - echo "script end"
after_success:
  - codecov
  - python3 -m flake8 fracdiff
  - python3 -m black --check fracdiff
  - python3 -m isort --check --force-single-line-imports fracdiff
